Ajustement
JohnP55/DarQuest pull request #13
Opened 2023-03-31 18:50 UTC by Novatruepower

Le positionnement du modal reste à faire, ainsi que ajouter l'objet au panier

2023-03-31 19:58 UTC, JohnP55 requested changes
isch

2023-03-31 19:58 UTC, JohnP55 commented on consulterInventaire.php
>    require_once("functions/db.php");
require_once("functions/db.php") existe deux fois

2023-03-31 19:58 UTC, JohnP55 commented on consulterInventaire.php
> +  $navbar = (isset($_SESSION["idPlayer"]) && $_SESSION["idPlayer"] > 0) ? "partial/full-navbar-template.php" : "partial/guest-navbar-template.php";
Ce check n'est plus nécessaire puisqu'il existe dans navbar-template.php
Et de toute façon, puisque l'utilisateur doit forcément être connecté, ça sera toujours le full-navbar-template.

2023-03-31 19:58 UTC, JohnP55 commented on consulterInventaire.php
> +  $navbar = (isset($_SESSION["idPlayer"]) && $_SESSION["idPlayer"] > 0) ? "partial/full-navbar-template.php" : "partial/guest-navbar-template.php";
Aussi, mets pas la navbar dans le \<head\>

2023-03-31 19:58 UTC, JohnP55 commented on functions/consulterInventaireFunctions.php
>  <?php
Ce fichier sert pour des fonctions php, mets pas du CSS dedans

2023-03-31 19:58 UTC, JohnP55 commented on functions/indexFunctions.php
> +</style>
mets pas de CSS dans un fichier de fonctions PHP

2023-03-31 19:58 UTC, JohnP55 commented on functions/indexFunctions.php
> +<div style="display: block;"></div>
mets pas d'éléments HTML dans un fichier de fonctions PHP

2023-03-31 19:58 UTC, JohnP55 commented on functions/consulterInventaireFunctions.php
>  <?php
Mets tous tes styles dans un fichier .css

2023-03-31 19:58 UTC, JohnP55 commented on functions/itemFunctions.php
> +</style>
mets pas de styles CSS dans un fichier de fonctions PHP

2023-03-31 19:58 UTC, JohnP55 commented on item.php
> +    <div class="modal fade" id="cartItemModal" tabindex="-1" aria-labelledby="cartItemModalLabel" aria-hidden="true">
C'est pas un cartItem

2023-03-31 19:58 UTC, JohnP55 commented on item.php
> +      const addButton = $("#add-item");7
7

2023-03-31 19:58 UTC, JohnP55 commented on partial/mustBeLog.php
> +    session_start();
est-ce que tu as besoin de faire ce check? on devrait mieux s'assurer de bien organiser les session_start()

2023-04-01 07:26 UTC, BuyMyBeard commented on index.php
lol

2023-04-01 19:01 UTC, JohnP55 approved these changes

2023-04-01 19:02 UTC, JohnP55 approved these changes

2023-04-01 19:02 UTC, merged